// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HousePriceAPI.DataModels
{
    public class HousePriceData
    {
        [ColumnName("Rooms"), LoadColumn(0)]
        public float Rooms { get; set; }


        [ColumnName("Surface"), LoadColumn(1)]
        public float Surface { get; set; }


        [ColumnName("Location"), LoadColumn(2)]
        public float Location { get; set; }


        [ColumnName("Price"), LoadColumn(3)]
        public float Price { get; set; }


    }
}
