// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace HousePriceAPI.DataModels
{
    public class HousePricePrediction
    {
        public float Score { get; set; }
    }
}
